version: '3.8'

services:
  mysql_restaurante:
    image: mysql:latest
    container_name: tallerCompose
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: restaurante 
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./restaurante.sql:/docker-entrypoint-initdb.d/restaurante.sql  

volumes:
  mysql_data:
